### ISSUE TITLE
APT parser dithering unit test failure

### ISSUE THREAD

**Issue by vcgeers** [JWST-MIRI/MiriTE#17]
Hi Christophe,

I just got a notification that the Jenkins build for MiriTE failed. The log shows that one of the unit tests for APT parser threw an error:
apt_parser/tests/test_dithering.py

======================================================================
ERROR: Test of dithering
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/export/disk/anaconda2019.07/envs/miricleDevel36/lib/python3.6/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/export/disk/anaconda2019.07/envs/miricleDevel36/lib/python3.6/site-packages/parameterized/parameterized.py", line 387, in <lambda>
    nose_func = wraps(func)(lambda *args: func(*args[:-1], **args[-1]))
  File "/var/lib/jenkins/workspace/MiriTE_devel/apt_parser/tests/test_dithering.py", line 58, in test_dithering
    nb_dither = parse_dither(tree, namespace)
  File "/export/disk/anaconda2019.07/envs/miricleDevel36/lib/python3.6/site-packages/miri/apt_parser/dithering.py", line 51, in parse_dither
    return nb_dither_points
UnboundLocalError: local variable 'nb_dither_points' referenced before assignment
-------------------- >> begin captured logging << --------------------
miri.apt_parser.dithering: ERROR: Unable to retrieve number of dither points from CYCLING-MICRO

Could you please take a look?

**Comment by ccossou** [comment]
Yes, I got the same error locally. But since I got big trouble to run unit test with MIRI TE because it doesn't work with the develop version, I assumed it would work with the unit test. 

When I created the pull request, I also assumed the unitest were run in the background and would insult me in case one test failed. 

I would be very interested @vcgeers if you could explain to me how you run unittest locally when you change the code every 5 minutes. This is a big problem for my workflow with MiriTE right now (see https://github.com/JWST-MIRI/MiriTE/issues/6 )

**Comment by ccossou** [comment]
Since the code work on my computer, I don't really understand why the test fail to be honest.

I just ran my script with the latest version of MiriTE and it works. What I can't test is the unit test itself because I can't run the nosetests unless I break completely my version of miricle.devel.

**Comment by vcgeers** [comment]
For me, it's not trivial running the unit tests for MiriTE either, because the presence of an __init__.py under the top-level mirite.git directory is fooling nosetests into thinking that the module name is "mirite", rather than "miri". I think the planned restructure would address this.

If I temporarily remove that top-level __init__.py, then I can run the unit tests, but that isn't a great solution. I'm not sure how Steven runs the unit tests locally; perhaps he runs them within the installed package under site-packages.

W.r.t. Pull Requests and unit tests: currently, the Jenkins build system is hosted by Leuven, completely separate from GitHub, and it's only monitoring master. What you are looking for is CI solution, such as Travis provides for GitHub projects. We have not looked into setting up something like that.

**Comment by ccossou** [comment]
I just successfully ran the unit test locally. 
On what version of MiriTE is the build system working? Because I noticed a few weeks ago that some old code I added in apt_parser was not in miricle.devel. 

Maybe there's something that needs to be done to include it in miricle.devel. Can it be something related to that?

**Comment by vcgeers** [comment]
Hmm, I've added Wim to the conversation.

I note that the Jenkins build for MiriTE also reports unit test failures for Noise related tests, even after Steven reverted a recent commit that seemingly caused the failure. So maybe indeed somehow the MiriTE build is not actually picking up the latest commit.

**Comment by smbeard** [comment]
I usually run individual unit tests by running just the test module associated with the code I changed, such as

$ cd datamodels/tests
$ python test_flatfield_model.py
Ran 20 tests in 9.181s

OK

Unfortunately, this doesn't work for test_dithering.py.

$ cd apt_parser/tests
$ python test_dithering.py

The python command just finishes instantly without running any tests. However, you can run nosetests within the subdirectory.

$ cd apt_parser/tests
$ nosetests
Ran 23 tests in 2.457s

OK

**Comment by ccossou** [comment]
Can you please give me the link to the website were the jenkins build is done? I couldn't find it in the "code repositories" page in the EC Twiki. I don't know if I can get something out of it, but I wanted to have a look.

**Comment by vcgeers** [comment]
Hi Steven,
That example of running nosetests directly within the subdirectory does not work for everyone, for the reason explained above; at least, not when running it within the repo clone directory.

I see the MiriTE build is back to stable. It's still not clear to me why the dithering test failed just after the commit that introduced the micro pattern, but is not failing now anymore (after seemingly no further updates to that bit of the code). Unfortunately, we have a lot of higher priority work to focus on, so unless someone has time to dig into this, I propose we close this.

**Comment by JuergenSchreiber** [comment]
https://jenkins.miricle.org/
Here you see all the building activity of the Leuven server, it is the build link on miricle.org
I use the python unittest run in eclipse after "compiling" the new code in the sitepackages ...eggs

**Comment by ccossou** [comment]
Thanks @JuergenSchreiber , bookmarked right away ! (I had it and seemingly lost it). 

@vcgeers : Agreed. I propose to open an issue "for later", to investigate the problem in the build process and the fact that the unit test fail when they should not. If the building process fail, then succeed with the same code, that's an indication that there's a lag somewhere and it could become crucial, for instance during commissioning if we have a tight schedule and simply wait for the building process to launch in an infinite loop until it succeed.

**Comment by vcgeers** [comment]
Sounds good Christophe. Probably best done on JIRA, since it may span various repos, and please add Wim as a watcher, as he is the primary person for the build system.

One thing to note is that the build system was recently transferred from the old to the new server, and in the process, the build system was apparently significantly simplified. Something like what we saw here may be a subtle bug related to this migration.

**Comment by ccossou** [comment]
Ticket Created: https://ukatcfaultlog.atlassian.net/browse/MIRI-779

Closing this one.
