### ISSUE TITLE
Developper install working differently than regular install

### ISSUE THREAD

**Issue by ccossou** [JWST-MIRI/MiriTE#6]
When developping, I'm used to install using developper mode:
```bash
pip install -e .
```
or 
```bash
python setup.py develop
```

However, it doesn't work for MiriTE because the package architecture is different than the Git structure (no folder named "miri" that contains all sub-modules for instance). 

You then cannot use the same import in developper mode and in installed mode

Installed mode:
```python
import miri.apt_parser
```

Developper mode:
```python
import apt_parser
```

Do you have the same problem? Have you found a solution to use the same scripts in both installations?

**Comment by ccossou** [comment]
I created a JIRA ticket for that: https://ukatcfaultlog.atlassian.net/browse/MIRI-759

**Comment by smbeard** [comment]
I haven't forgotten this issue. I am planning to wait until the CDP-8 and JWST build 7.4 test branches have been merged back with the master. I am not sure how the git merging would cope with the entire directory structure changing if I changed master before merging these test branches. If git can follow files even when they are renamed and/or moved into new subdirectories and merge them correctly I could make this change earlier. Perhaps a git expert could comment?

**Comment by ccossou** [comment]
Usually, when you move a file, git say "file renamed" or similar. So I think Git will keep track of the file, even when renamed. 

That being said, I'm not entirely sure, there's a difference between my assumption and the reality, and for something of that scale, maybe it's better to wait, if someone other than me can't say with certainty that what I describe is the reality.

**Comment by smbeard** [comment]
Maybe I don't have enough confidence in git? I guess one advantage of git is that you can create an experimental branch and try it out. I'll fork an experimental branch from master, change the directory structure and then try merging those other branches with it. If the experiment works I'll go ahead and make the change. If the merge fails I'll delete the experimental branch and carry on waiting.

**Comment by smbeard** [comment]
I have created a new branch in the MiriTE repository called new_structure with a new package structure. Try checking out this branch and see if it fixes the problem.

If it works I will create an experimental branch and test whether the cdp8_datamodels and testwithjwst0.15.0 branches will merge with it.

**Comment by ccossou** [comment]
New branch merged back into trunk, Thanks a lot Steven, this is perfect!
